name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (with distribution specified)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Use 'temurin' for Eclipse Adoptium (formerly AdoptOpenJDK)

      # Step 3: Make the gradlew file executable
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Step 4: Build the JAR file
      - name: Build JAR file using Gradle
        run: |
          ./gradlew build

      # Step 5: Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set in repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Set in repository secrets

      # Step 6: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      # Step 7: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Set in repository secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Set in repository secrets
          aws-region: ${{ secrets.AWS_REGION }} # Change to your AWS region (e.g., us-east-1)

      # Step 8: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 9: Tag the image and push to ECR
      - name: Tag and Push Docker image to ECR
        run: |
          docker tag myapp:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPO_NAME }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.REPO_NAME }}:latest

      # Step 10: Push Docker Image to DockerHub (optional)
      - name: Push Docker Image to DockerHub
        run: |
          docker tag myapp:latest oskarsmartinsons/myapp:latest
          docker push oskarsmartinsons/myapp:latest
