name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (with distribution specified)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # Specify the JDK distribution (you can use 'zulu', 'amazon-corretto', etc.)

      # Step 3: Build the JAR file
      - name: Build JAR file using Gradle
        run: |
          ./gradlew build

      # Step 4: Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Set in repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Set in repository secrets

      # Step 5: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      # Step 6: Push the Docker image to DockerHub
      - name: Push Docker Image to DockerHub
        run: |
          docker tag myapp:latest oskarsmartinsons/myapp:latest
          docker push oskarsmartinsons/myapp:latest

      # Step 7: Push Docker Image to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Set in repository secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Set in repository secrets
          aws-region: eu-west-3 # Change to your AWS region

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push to Amazon ECR
        run: |
          # Replace with your AWS account ID and ECR repository name
          AWS_ACCOUNT_ID=762233771900
          IMAGE_NAME=myapp
          REPO_NAME=my-ecr-repo
          
          # Tag and push image to ECR
          docker tag myapp:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:latest
